warp_mesh = "morph.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'mat_morph', 'mat_ears',  'mat_glasses',  'mat_lens', 'mat_nose']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_teeth_middle.png"
lookupTexEyes="lut3d_eyes_middle.png"
tex_softLight="soft_pleasant_make.png"
tex_normalMakeup="make_up.png"

# Cut
[materials.mat_morph]
vs = "mat_morph.vert"
fs = "mat_morph.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.mat_glasses]
vs = "mat_glasses.vert"
fs = "mat_glasses.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.mat_glasses.samplers]
tex_diffuse="glasses_Base_Color.ktx"
tex_normal="glasses_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="glasses_MRAO.ktx"

# PBR
[materials.mat_ears]
vs = "billboard.vert"
fs = "video_a.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
ztest = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.mat_lens]
vs = "mat_lens.vert"
fs = "mat_lens.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
[materials.mat_lens.samplers]
tex_diffuse="glasses_Base_Color.ktx"
tex_normal="glasses_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="glasses_MRAO.ktx"

# PBR
[materials.mat_nose]
vs = "billboard.vert"
fs = "sprite.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.mat_nose.samplers]
tex_diffuse="nose_Base_Color.ktx"