warp_mesh = "BeautyFaceSP.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'facemat', 'Hat', 'glass']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="soft_not_red_low.png"
tex_normalMakeup="unisex_minimal.png"
tex_highlight="FLARE_40_768.png"

# Cut
[materials.facemat]
vs = "facemat.vert"
fs = "facemat.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.Hat]
vs = "hat.vert"
fs = "video_a.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.Hat.samplers]
tex_diffuse="Hat_BaseColor.png"
tex_normal="Hat_Normal.png"
tex_metallic="Hat_Metallic.png"
tex_roughness="Hat_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_emi="Hat_BaseColor.png"

# PBR
[materials.glass]
vs = "glass.vert"
fs = "glass.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glass.samplers]
tex_diffuse=0
tex_normal="glass_Normal.png"
tex_metallic="glass_Metallic.png"
tex_roughness="glass_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"