warp_mesh = "BeautyFaceSP_Optimased.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'facemat', 'glasses', 'fur',  "!glfx_UPDATE_BG", 'TriMat']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
lookupTexTeeth="lut3d_TEETH_medium.png"
lookupTexEyes="lut3d_EYES_medium.png"
tex_softLight="soft.png"
tex_normalMakeup="makeup.png"
tex_highlight="FLARE_40_768.png"

# Cut
[materials.facemat]
vs = "facemat.vert"
fs = "facemat.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.glasses]
vs = "glasses.vert"
fs = "glasses.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = true
shadow = false
[materials.glasses.samplers]
tex_diffuse="glasses_BaseColor.png"
tex_normal="glasses_Normal.png"
tex_metallic="glasses_Metallic.png"
tex_roughness="glasses_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

# PBR
[materials.fur]
vs = "fur.vert"
fs = "fur.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = true
colorwrite = true
zwrite = false
shadow = false
[materials.fur.samplers]
tex_diffuse="glasses_BaseColor.png"
tex_normal="glasses_Normal.png"
tex_metallic="glasses_Metallic.png"
tex_roughness="glasses_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

[materials.TriMat]
vs = "fstri.vert"
fs = "glitch.frag"
blend = "off"
backfaces = true
shadow = false
zwrite = false
samplers = {}