warp_mesh = "Beauty06.bsm2"
draw_order = ["retouch", "Ear", "Nose"]

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
samplers = { selection_tex="REDMASK_v3_256.png", lookupTexTeeth="TEETH_medium.png", lookupTexEyes="EYES_medium.png", tex_highlight="FLARE_39_512.png", tex_makeup="rabbit_make2.png", tex_makeup2="soft.png"}

[materials.Ear]
vs = "billboard.vert"
fs = "video_a.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = true
zwrite = false
shadow = false
samplers = {}

[materials.Nose]
vs = "billboard.vert"
fs = "tex.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = true
colorwrite = true
zwrite = false
shadow = false
samplers = { tex = "rabbit_make2.png" }

